/**
 * This class is generated by jOOQ
 */
package com.loiane.mysql.generatedclasses.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CountryRecord extends org.jooq.impl.UpdatableRecordImpl<com.loiane.mysql.generatedclasses.tables.records.CountryRecord> implements org.jooq.Record15<java.lang.String, java.lang.String, com.loiane.mysql.generatedclasses.enums.CountryContinent, java.lang.String, java.lang.Double, java.lang.Short, java.lang.Integer, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = -1733315616;

	/**
	 * Setter for <code>world.Country.Code</code>. 
	 */
	public void setCode(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>world.Country.Code</code>. 
	 */
	public java.lang.String getCode() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>world.Country.Name</code>. 
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>world.Country.Name</code>. 
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>world.Country.Continent</code>. 
	 */
	public void setContinent(com.loiane.mysql.generatedclasses.enums.CountryContinent value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>world.Country.Continent</code>. 
	 */
	public com.loiane.mysql.generatedclasses.enums.CountryContinent getContinent() {
		return (com.loiane.mysql.generatedclasses.enums.CountryContinent) getValue(2);
	}

	/**
	 * Setter for <code>world.Country.Region</code>. 
	 */
	public void setRegion(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>world.Country.Region</code>. 
	 */
	public java.lang.String getRegion() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>world.Country.SurfaceArea</code>. 
	 */
	public void setSurfacearea(java.lang.Double value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>world.Country.SurfaceArea</code>. 
	 */
	public java.lang.Double getSurfacearea() {
		return (java.lang.Double) getValue(4);
	}

	/**
	 * Setter for <code>world.Country.IndepYear</code>. 
	 */
	public void setIndepyear(java.lang.Short value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>world.Country.IndepYear</code>. 
	 */
	public java.lang.Short getIndepyear() {
		return (java.lang.Short) getValue(5);
	}

	/**
	 * Setter for <code>world.Country.Population</code>. 
	 */
	public void setPopulation(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>world.Country.Population</code>. 
	 */
	public java.lang.Integer getPopulation() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>world.Country.LifeExpectancy</code>. 
	 */
	public void setLifeexpectancy(java.lang.Double value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>world.Country.LifeExpectancy</code>. 
	 */
	public java.lang.Double getLifeexpectancy() {
		return (java.lang.Double) getValue(7);
	}

	/**
	 * Setter for <code>world.Country.GNP</code>. 
	 */
	public void setGnp(java.lang.Double value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>world.Country.GNP</code>. 
	 */
	public java.lang.Double getGnp() {
		return (java.lang.Double) getValue(8);
	}

	/**
	 * Setter for <code>world.Country.GNPOld</code>. 
	 */
	public void setGnpold(java.lang.Double value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>world.Country.GNPOld</code>. 
	 */
	public java.lang.Double getGnpold() {
		return (java.lang.Double) getValue(9);
	}

	/**
	 * Setter for <code>world.Country.LocalName</code>. 
	 */
	public void setLocalname(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>world.Country.LocalName</code>. 
	 */
	public java.lang.String getLocalname() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>world.Country.GovernmentForm</code>. 
	 */
	public void setGovernmentform(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>world.Country.GovernmentForm</code>. 
	 */
	public java.lang.String getGovernmentform() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>world.Country.HeadOfState</code>. 
	 */
	public void setHeadofstate(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>world.Country.HeadOfState</code>. 
	 */
	public java.lang.String getHeadofstate() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>world.Country.Capital</code>. 
	 */
	public void setCapital(java.lang.Integer value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>world.Country.Capital</code>. 
	 */
	public java.lang.Integer getCapital() {
		return (java.lang.Integer) getValue(13);
	}

	/**
	 * Setter for <code>world.Country.Code2</code>. 
	 */
	public void setCode2(java.lang.String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>world.Country.Code2</code>. 
	 */
	public java.lang.String getCode2() {
		return (java.lang.String) getValue(14);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record15 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row15<java.lang.String, java.lang.String, com.loiane.mysql.generatedclasses.enums.CountryContinent, java.lang.String, java.lang.Double, java.lang.Short, java.lang.Integer, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row15) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row15<java.lang.String, java.lang.String, com.loiane.mysql.generatedclasses.enums.CountryContinent, java.lang.String, java.lang.Double, java.lang.Short, java.lang.Integer, java.lang.Double, java.lang.Double, java.lang.Double, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row15) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.loiane.mysql.generatedclasses.tables.Country.COUNTRY.CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.loiane.mysql.generatedclasses.tables.Country.COUNTRY.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<com.loiane.mysql.generatedclasses.enums.CountryContinent> field3() {
		return com.loiane.mysql.generatedclasses.tables.Country.COUNTRY.CONTINENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.loiane.mysql.generatedclasses.tables.Country.COUNTRY.REGION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field5() {
		return com.loiane.mysql.generatedclasses.tables.Country.COUNTRY.SURFACEAREA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field6() {
		return com.loiane.mysql.generatedclasses.tables.Country.COUNTRY.INDEPYEAR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return com.loiane.mysql.generatedclasses.tables.Country.COUNTRY.POPULATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field8() {
		return com.loiane.mysql.generatedclasses.tables.Country.COUNTRY.LIFEEXPECTANCY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field9() {
		return com.loiane.mysql.generatedclasses.tables.Country.COUNTRY.GNP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field10() {
		return com.loiane.mysql.generatedclasses.tables.Country.COUNTRY.GNPOLD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return com.loiane.mysql.generatedclasses.tables.Country.COUNTRY.LOCALNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return com.loiane.mysql.generatedclasses.tables.Country.COUNTRY.GOVERNMENTFORM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field13() {
		return com.loiane.mysql.generatedclasses.tables.Country.COUNTRY.HEADOFSTATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field14() {
		return com.loiane.mysql.generatedclasses.tables.Country.COUNTRY.CAPITAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field15() {
		return com.loiane.mysql.generatedclasses.tables.Country.COUNTRY.CODE2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.loiane.mysql.generatedclasses.enums.CountryContinent value3() {
		return getContinent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getRegion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value5() {
		return getSurfacearea();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value6() {
		return getIndepyear();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getPopulation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value8() {
		return getLifeexpectancy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value9() {
		return getGnp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value10() {
		return getGnpold();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getLocalname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getGovernmentform();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value13() {
		return getHeadofstate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value14() {
		return getCapital();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value15() {
		return getCode2();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CountryRecord
	 */
	public CountryRecord() {
		super(com.loiane.mysql.generatedclasses.tables.Country.COUNTRY);
	}

	/**
	 * Create a detached, initialised CountryRecord
	 */
	public CountryRecord(java.lang.String code, java.lang.String name, com.loiane.mysql.generatedclasses.enums.CountryContinent continent, java.lang.String region, java.lang.Double surfacearea, java.lang.Short indepyear, java.lang.Integer population, java.lang.Double lifeexpectancy, java.lang.Double gnp, java.lang.Double gnpold, java.lang.String localname, java.lang.String governmentform, java.lang.String headofstate, java.lang.Integer capital, java.lang.String code2) {
		super(com.loiane.mysql.generatedclasses.tables.Country.COUNTRY);

		setValue(0, code);
		setValue(1, name);
		setValue(2, continent);
		setValue(3, region);
		setValue(4, surfacearea);
		setValue(5, indepyear);
		setValue(6, population);
		setValue(7, lifeexpectancy);
		setValue(8, gnp);
		setValue(9, gnpold);
		setValue(10, localname);
		setValue(11, governmentform);
		setValue(12, headofstate);
		setValue(13, capital);
		setValue(14, code2);
	}
}
