/**
 * This class is generated by jOOQ
 */
package com.loiane.mysql.generatedclasses.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CountrylanguageRecord extends org.jooq.impl.UpdatableRecordImpl<com.loiane.mysql.generatedclasses.tables.records.CountrylanguageRecord> implements org.jooq.Record4<java.lang.String, java.lang.String, com.loiane.mysql.generatedclasses.enums.CountrylanguageIsofficial, java.lang.Double> {

	private static final long serialVersionUID = -1882772304;

	/**
	 * Setter for <code>world.CountryLanguage.CountryCode</code>. 
	 */
	public void setCountrycode(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>world.CountryLanguage.CountryCode</code>. 
	 */
	public java.lang.String getCountrycode() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>world.CountryLanguage.Language</code>. 
	 */
	public void setLanguage(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>world.CountryLanguage.Language</code>. 
	 */
	public java.lang.String getLanguage() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>world.CountryLanguage.IsOfficial</code>. 
	 */
	public void setIsofficial(com.loiane.mysql.generatedclasses.enums.CountrylanguageIsofficial value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>world.CountryLanguage.IsOfficial</code>. 
	 */
	public com.loiane.mysql.generatedclasses.enums.CountrylanguageIsofficial getIsofficial() {
		return (com.loiane.mysql.generatedclasses.enums.CountrylanguageIsofficial) getValue(2);
	}

	/**
	 * Setter for <code>world.CountryLanguage.Percentage</code>. 
	 */
	public void setPercentage(java.lang.Double value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>world.CountryLanguage.Percentage</code>. 
	 */
	public java.lang.Double getPercentage() {
		return (java.lang.Double) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.String, java.lang.String> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.String, com.loiane.mysql.generatedclasses.enums.CountrylanguageIsofficial, java.lang.Double> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.String, com.loiane.mysql.generatedclasses.enums.CountrylanguageIsofficial, java.lang.Double> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.loiane.mysql.generatedclasses.tables.Countrylanguage.COUNTRYLANGUAGE.COUNTRYCODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.loiane.mysql.generatedclasses.tables.Countrylanguage.COUNTRYLANGUAGE.LANGUAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<com.loiane.mysql.generatedclasses.enums.CountrylanguageIsofficial> field3() {
		return com.loiane.mysql.generatedclasses.tables.Countrylanguage.COUNTRYLANGUAGE.ISOFFICIAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field4() {
		return com.loiane.mysql.generatedclasses.tables.Countrylanguage.COUNTRYLANGUAGE.PERCENTAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getCountrycode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getLanguage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.loiane.mysql.generatedclasses.enums.CountrylanguageIsofficial value3() {
		return getIsofficial();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value4() {
		return getPercentage();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CountrylanguageRecord
	 */
	public CountrylanguageRecord() {
		super(com.loiane.mysql.generatedclasses.tables.Countrylanguage.COUNTRYLANGUAGE);
	}

	/**
	 * Create a detached, initialised CountrylanguageRecord
	 */
	public CountrylanguageRecord(java.lang.String countrycode, java.lang.String language, com.loiane.mysql.generatedclasses.enums.CountrylanguageIsofficial isofficial, java.lang.Double percentage) {
		super(com.loiane.mysql.generatedclasses.tables.Countrylanguage.COUNTRYLANGUAGE);

		setValue(0, countrycode);
		setValue(1, language);
		setValue(2, isofficial);
		setValue(3, percentage);
	}
}
