/**
 * This class is generated by jOOQ
 */
package com.loiane.mysql.generatedclasses.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class City extends org.jooq.impl.TableImpl<com.loiane.mysql.generatedclasses.tables.records.CityRecord> {

	private static final long serialVersionUID = 256279204;

	/**
	 * The singleton instance of <code>world.City</code>
	 */
	public static final com.loiane.mysql.generatedclasses.tables.City CITY = new com.loiane.mysql.generatedclasses.tables.City();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.loiane.mysql.generatedclasses.tables.records.CityRecord> getRecordType() {
		return com.loiane.mysql.generatedclasses.tables.records.CityRecord.class;
	}

	/**
	 * The column <code>world.City.ID</code>. 
	 */
	public final org.jooq.TableField<com.loiane.mysql.generatedclasses.tables.records.CityRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>world.City.Name</code>. 
	 */
	public final org.jooq.TableField<com.loiane.mysql.generatedclasses.tables.records.CityRecord, java.lang.String> NAME = createField("Name", org.jooq.impl.SQLDataType.CHAR.length(35).nullable(false).defaulted(true), this);

	/**
	 * The column <code>world.City.CountryCode</code>. 
	 */
	public final org.jooq.TableField<com.loiane.mysql.generatedclasses.tables.records.CityRecord, java.lang.String> COUNTRYCODE = createField("CountryCode", org.jooq.impl.SQLDataType.CHAR.length(3).nullable(false).defaulted(true), this);

	/**
	 * The column <code>world.City.District</code>. 
	 */
	public final org.jooq.TableField<com.loiane.mysql.generatedclasses.tables.records.CityRecord, java.lang.String> DISTRICT = createField("District", org.jooq.impl.SQLDataType.CHAR.length(20).nullable(false).defaulted(true), this);

	/**
	 * The column <code>world.City.Population</code>. 
	 */
	public final org.jooq.TableField<com.loiane.mysql.generatedclasses.tables.records.CityRecord, java.lang.Integer> POPULATION = createField("Population", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this);

	/**
	 * Create a <code>world.City</code> table reference
	 */
	public City() {
		super("City", com.loiane.mysql.generatedclasses.World.WORLD);
	}

	/**
	 * Create an aliased <code>world.City</code> table reference
	 */
	public City(java.lang.String alias) {
		super(alias, com.loiane.mysql.generatedclasses.World.WORLD, com.loiane.mysql.generatedclasses.tables.City.CITY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.loiane.mysql.generatedclasses.tables.records.CityRecord, java.lang.Integer> getIdentity() {
		return com.loiane.mysql.generatedclasses.Keys.IDENTITY_CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.loiane.mysql.generatedclasses.tables.records.CityRecord> getPrimaryKey() {
		return com.loiane.mysql.generatedclasses.Keys.KEY_CITY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.loiane.mysql.generatedclasses.tables.records.CityRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.loiane.mysql.generatedclasses.tables.records.CityRecord>>asList(com.loiane.mysql.generatedclasses.Keys.KEY_CITY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.loiane.mysql.generatedclasses.tables.City as(java.lang.String alias) {
		return new com.loiane.mysql.generatedclasses.tables.City(alias);
	}
}
