/**
 * This class is generated by jOOQ
 */
package com.loiane.mysql.generatedclasses.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Countrylanguage extends org.jooq.impl.TableImpl<com.loiane.mysql.generatedclasses.tables.records.CountrylanguageRecord> {

	private static final long serialVersionUID = 1650391458;

	/**
	 * The singleton instance of <code>world.CountryLanguage</code>
	 */
	public static final com.loiane.mysql.generatedclasses.tables.Countrylanguage COUNTRYLANGUAGE = new com.loiane.mysql.generatedclasses.tables.Countrylanguage();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.loiane.mysql.generatedclasses.tables.records.CountrylanguageRecord> getRecordType() {
		return com.loiane.mysql.generatedclasses.tables.records.CountrylanguageRecord.class;
	}

	/**
	 * The column <code>world.CountryLanguage.CountryCode</code>. 
	 */
	public final org.jooq.TableField<com.loiane.mysql.generatedclasses.tables.records.CountrylanguageRecord, java.lang.String> COUNTRYCODE = createField("CountryCode", org.jooq.impl.SQLDataType.CHAR.length(3).nullable(false).defaulted(true), this);

	/**
	 * The column <code>world.CountryLanguage.Language</code>. 
	 */
	public final org.jooq.TableField<com.loiane.mysql.generatedclasses.tables.records.CountrylanguageRecord, java.lang.String> LANGUAGE = createField("Language", org.jooq.impl.SQLDataType.CHAR.length(30).nullable(false).defaulted(true), this);

	/**
	 * The column <code>world.CountryLanguage.IsOfficial</code>. 
	 */
	public final org.jooq.TableField<com.loiane.mysql.generatedclasses.tables.records.CountrylanguageRecord, com.loiane.mysql.generatedclasses.enums.CountrylanguageIsofficial> ISOFFICIAL = createField("IsOfficial", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.loiane.mysql.generatedclasses.enums.CountrylanguageIsofficial.class), this);

	/**
	 * The column <code>world.CountryLanguage.Percentage</code>. 
	 */
	public final org.jooq.TableField<com.loiane.mysql.generatedclasses.tables.records.CountrylanguageRecord, java.lang.Double> PERCENTAGE = createField("Percentage", org.jooq.impl.SQLDataType.FLOAT.nullable(false).defaulted(true), this);

	/**
	 * Create a <code>world.CountryLanguage</code> table reference
	 */
	public Countrylanguage() {
		super("CountryLanguage", com.loiane.mysql.generatedclasses.World.WORLD);
	}

	/**
	 * Create an aliased <code>world.CountryLanguage</code> table reference
	 */
	public Countrylanguage(java.lang.String alias) {
		super(alias, com.loiane.mysql.generatedclasses.World.WORLD, com.loiane.mysql.generatedclasses.tables.Countrylanguage.COUNTRYLANGUAGE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.loiane.mysql.generatedclasses.tables.records.CountrylanguageRecord> getPrimaryKey() {
		return com.loiane.mysql.generatedclasses.Keys.KEY_COUNTRYLANGUAGE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.loiane.mysql.generatedclasses.tables.records.CountrylanguageRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.loiane.mysql.generatedclasses.tables.records.CountrylanguageRecord>>asList(com.loiane.mysql.generatedclasses.Keys.KEY_COUNTRYLANGUAGE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.loiane.mysql.generatedclasses.tables.Countrylanguage as(java.lang.String alias) {
		return new com.loiane.mysql.generatedclasses.tables.Countrylanguage(alias);
	}
}
