/**
 * This class is generated by jOOQ
 */
package com.loiane.mysql.generatedclasses;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>world</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<com.loiane.mysql.generatedclasses.tables.records.CityRecord, java.lang.Integer> IDENTITY_CITY = Identities0.IDENTITY_CITY;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.loiane.mysql.generatedclasses.tables.records.CityRecord> KEY_CITY_PRIMARY = UniqueKeys0.KEY_CITY_PRIMARY;
	public static final org.jooq.UniqueKey<com.loiane.mysql.generatedclasses.tables.records.CountryRecord> KEY_COUNTRY_PRIMARY = UniqueKeys0.KEY_COUNTRY_PRIMARY;
	public static final org.jooq.UniqueKey<com.loiane.mysql.generatedclasses.tables.records.CountrylanguageRecord> KEY_COUNTRYLANGUAGE_PRIMARY = UniqueKeys0.KEY_COUNTRYLANGUAGE_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<com.loiane.mysql.generatedclasses.tables.records.CityRecord, java.lang.Integer> IDENTITY_CITY = createIdentity(com.loiane.mysql.generatedclasses.tables.City.CITY, com.loiane.mysql.generatedclasses.tables.City.CITY.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.loiane.mysql.generatedclasses.tables.records.CityRecord> KEY_CITY_PRIMARY = createUniqueKey(com.loiane.mysql.generatedclasses.tables.City.CITY, com.loiane.mysql.generatedclasses.tables.City.CITY.ID);
		public static final org.jooq.UniqueKey<com.loiane.mysql.generatedclasses.tables.records.CountryRecord> KEY_COUNTRY_PRIMARY = createUniqueKey(com.loiane.mysql.generatedclasses.tables.Country.COUNTRY, com.loiane.mysql.generatedclasses.tables.Country.COUNTRY.CODE);
		public static final org.jooq.UniqueKey<com.loiane.mysql.generatedclasses.tables.records.CountrylanguageRecord> KEY_COUNTRYLANGUAGE_PRIMARY = createUniqueKey(com.loiane.mysql.generatedclasses.tables.Countrylanguage.COUNTRYLANGUAGE, com.loiane.mysql.generatedclasses.tables.Countrylanguage.COUNTRYLANGUAGE.COUNTRYCODE, com.loiane.mysql.generatedclasses.tables.Countrylanguage.COUNTRYLANGUAGE.LANGUAGE);
	}
}
