/**
 * This class is generated by jOOQ
 */
package com.loiane.mysql.generatedclasses;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in world
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table world.City
	 */
	public static final com.loiane.mysql.generatedclasses.tables.City CITY = com.loiane.mysql.generatedclasses.tables.City.CITY;

	/**
	 * The table world.Country
	 */
	public static final com.loiane.mysql.generatedclasses.tables.Country COUNTRY = com.loiane.mysql.generatedclasses.tables.Country.COUNTRY;

	/**
	 * The table world.CountryLanguage
	 */
	public static final com.loiane.mysql.generatedclasses.tables.Countrylanguage COUNTRYLANGUAGE = com.loiane.mysql.generatedclasses.tables.Countrylanguage.COUNTRYLANGUAGE;
}
